name: Dataverse tests

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    # run workflow when merging to main or develop
    branches:
      - main
      - master
      - develop

env:
  KBASE_AUTH_TOKEN: ${{ secrets.KBASE_AUTH_TOKEN }}

jobs:

  collections_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:

    - name: Repo checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install pipenv
        pipenv sync --system --dev

    - name: Set kbase_auth_token
      run: |
        FILE=test/test.cfg
        LINE="kbase_auth_token = "$KBASE_AUTH_TOKEN""
        sed -i "s/^kbase_auth_token.*/$LINE/" $FILE
        cat test/test.cfg

    - name: Run tests
      shell: bash
      run: PYTHONPATH=. pytest --cov=src --cov-report=xml test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false